config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users

  resources :users do
    resource :profile
  end

  resources :listings do
    resources :orders, only: [:new, :create, :destroy, :edit]
    collection do
      get 'search'
    end
  end
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"

  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	# if else to enable localhost pic savings to go to computer and heroku savings go to dropbox - see gitignore file for more detail
	# figaro heroku:set -e production now instead of figaro:rake
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	else
	  has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
											:storage => :dropbox,
											:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
											:path => ":style/:id_:filename"
	end

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # data validation for listings  - nothing can be blank
  validates :name, :description, :price, presence: true
  # Check price field is both a number and is positive
  validates :price, numericality: { greater_than: 0 }
  # validation for presence of an image. Don't want listing to be saved with no image. Paperclip documentation
  validates_attachment_presence :image

# Associations
belongs_to :user
belongs_to :category
has_many :orders

searchkick
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def search
    if params[:search].present?
      @listings = Listing.search(params[:search])
    else
      @listings = Listing.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>12)
    end
  end


  # GET /seller
  # Show listings which are by the current user
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    if params[:category].blank?
      @listings = Listing.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>12)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @listings = Listing.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page =>12)
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    # set the user id for the created listing to the current user id
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :category_id, :description, :price, :image)
    end

    # created method to check that only user who owns a listing can change it - added to before_filter
    def check_user
      if current_user != @listing.user
        redirect_to root_utl, alert: "Sorry, You cannot modify this listing. It belongs to somebody else!"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true}) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Give yourself some Retail Therapy!</h1>
  <h2>Discover what it feels like to love yourself </h2>
</div>

<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
        <!-- image now set to be a link -->
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p>Price: <%= number_to_currency(listing.price) %></p>
            <p>Sold by: <%= listing.user.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<!-- Pagination centered with Bootstrap styling from will_paginate-bootstrap gem. Pagination set to limit 12 per page -->
<Div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</Div>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary" %>
<% end %>

<br>
<div class="center">
  <div class="fb-like" data-href="https://mrketplce.herokuapp.com/" data-layout="box_count" data-action="like" data-show-faces="false" data-share="false">
  </div class="center">
    <a href="https://twitter.com/I_amBradley" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @I_amBradley</a>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/search.html.erb
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
        <!-- image now set to be a link -->
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p>Price: <%= number_to_currency(listing.price) %></p>
            <p>Sold by: <%= listing.user.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<!-- Pagination centered with Bootstrap styling from will_paginate-bootstrap gem. Pagination set to limit 12 per page -->
<Div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</Div>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary" %>
<% end %>

<br>
<div class="center">
  <div class="fb-like" data-href="https://mrketplce.herokuapp.com/" data-layout="box_count" data-action="like" data-show-faces="false" data-share="false">
  </div class="center">
    <a href="https://twitter.com/I_amBradley" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @I_amBradley</a>
</div>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">action</th>
  </tr>

  <% @listings.each do |listing| %>
  <tr>
    <td><%= image_tag listing.image.url(:thumb) %></td>
    <td><%= listing.name %></td>
    <td><%= listing.description %></td>
    <td><%= number_to_currency(listing.price) %></td>
    <td>
    <!-- Split button -->
      <div class="btn-group">
        <button type="button" class="btn btn-default">Action</button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "View", listing, class: "btn btn-link" %></li>
          <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
          <li><%= link_to "Destroy", listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"%></li>
        </ul>
      </div>
    </td>
  </tr>
  <% end %>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>
		<p>Sold by: <%= @listing.user.name %></p>
		<%= link_to "But it Now", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
	</div>
</div>

<% if current_user == @listing.user %>
	<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>