config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users

  resources :users do
    resource :profile
  end

  resources :listings do
    resources :orders, only: [:new, :create, :destroy, :edit]
    collection do
      get 'search'
    end
  end
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"

  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
	# order validations
	validates :address, :city, :country, presence: true

	belongs_to :listing
	# class_name relates buyer and seller as a kind of User
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  # User must be signed in to make an order
  before_action :authenticate_user!

  # order history pages actions
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    # allows for listing id of ordered product to be found in the url
    @listing = Listing.find(params[:listing_id])
    # seller is the same as the user who created the listing
    @seller = @listing.user

    # the 3 new data entries in the order database (listing_id buyer_id seller_id)
    @order.listing_id = @listing.id
    # current user will be the buyer id of the order
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    # Stripe payment code
    # Tell Stripe our secret key to charge card 
    Stripe.api_key = ENV["STRIPE_API_KEY"]
    # params pulls token from hidden form field and set as variable token
    token = params[:stripeToken]

    # code from API page to charge a card https://stripe.com/docs/api#create_charge
    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => "eur",
        :card => token
        )
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :country)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price) %></h4>
  </div>
  <div class="col-md-8">
    <!-- parameters added to allow rails to find the listing id for each order -->
    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <!-- stripe error notification -->
      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>Javascript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :country %>
        <%= f.text_field :country, class: "form-control" %>
      </div>

      <!-- FROM SECTION FOR STRIPE CREDIT CARD DETAILS -->

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>

        <div class="form-group">
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digits_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div> <!-- end form-group -->
      <!-- END STRIPE -->

      <div class="form-group">
        <%= f.submit "Complete Order", class: "btn btn-success" %>
      </div>
    <% end %>
  </div> <!-- end of col-md-8 -->
</div> <!-- end of row -->

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/orders/purchases.html.erb
<div class="center">
	<h2> Your Purchase History </h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
  <tr>
    <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
    <td class="center"><%= order.listing.name %></td>
    <td class="center"><%= number_to_currency(order.listing.price) %></td>
    <td class="center"><%= order.seller.name %></td>
    <!-- got strftime method details from ruby-doc.org -->
    <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
  </tr>
  <% end %>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
	<h2> Your Sales History </h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.buyer.name %></td>
      <!-- got strftime method details from ruby-doc.org -->
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>