config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users

  resources :users do
    resource :profile
  end

  resources :listings do
    resources :orders, only: [:new, :create, :destroy, :edit]
    collection do
      get 'search'
    end
  end
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"

  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="muted credit">Copyright 2015 <a href="http://iambradley.me">Bradley</a>. </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MRKETPLCE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact Us", pages_contact_path %></li>
        <!-- Start of browse dropdown category dropdown -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user && current_user.admin? %>
              <li><%= link_to "Add Category", categories_path %></li>
            <% end %>
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, listings_path(category: category.name) %></li>
            <% end %>
          </ul>
          <li>
            <!-- search bar -->
            <%= form_tag search_listings_path, method: :get, class: "navbar-form navbar-left" do %>
              <p>
                <%= text_field_tag :search, params[:search], class: "form-control" %>
                <%= submit_tag "Search", name: nil, class: "btn btn-btn-default" %>
              </p>
            <% end %>
          </li>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!-- Seller account dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Listings", seller_path %></li>
              <li><%= link_to "Sales history", sales_path %></li>
            </ul>
          </li>
          <!-- Account details dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Purchases history", purchases_path %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <!-- hide create profile if profile already set up -->
              <% if current_user.profile %>
                <!-- edit_user_profile_path entered with parameter differently to remind me of other way can be written -->
                <li><%= link_to "Edit Profile", edit_user_profile_path(user_id: current_user.id) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_user_profile_path(current_user) if current_user %></li>
              <% end %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>

          <li><%= link_to "Sign In", new_user_session_path %></li>  
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_twitter.html.erb
<script>!function(d,s,id) {
var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
if (!d.getElementById(id)) {
	js=d.createElement(s);
	js.id=id;js.src=p+'://platform.twitter.com/widgets.js';
	fjs.parentNode.insertBefore(js,fjs);
}}
(document, 'script', 'twitter-wjs');</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mrketplce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
<div id="wrap">
	<%= render 'layouts/facebook' %>
	<%= render 'layouts/twitter' %>

	<%= render 'layouts/header' %>

	<div class="container">

		<% flash.each do |name, msg| %>
			<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name == :notice ? "danger" : "success" %> alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				</div>
			<% end %>
		<% end %>

		<%= yield %>
	</div>
 <!-- push id for sticky footer to work -->
	<div id="push"></div>

	<%= render 'layouts/footer' %>

</div>

</body>
</html>